const MOCK_PARTICIPANTS = [
  {
    id: 'p-1',
    rank: 1,
    name: 'Aarav Sharma',
    handle: '@aarav_builds',
    university: 'IIT Delhi',
    city: 'New Delhi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    category: 'TECH',
    isTeam: false,
    totalEarnings: 284500,
    earningsToday: 18500,
    earningsWeek: 64200,
    verifiedCount: 14,
    rankDelta24h: 1,
    isVelocityHigh: true,
    hustleTitle: 'Micro-SaaS Founder (FormFlow AI)',
    proofs: [
      {
        id: 'prf-101',
        amount: 18500,
        description: 'Stripe Connect (FormFlow AI US client)',
        category: 'TECH',
        timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
        proofUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        status: 'VERIFIED',
        clientType: 'Direct Stripe Payout',
        sanitizedDetails: {
          platform: 'Stripe Connect',
          transactionId: 'TXN-984214',
          redactedClient: '[Redacted Client LLC]',
          verifiedBy: 'EYFI Auto-Audit Engine',
        },
      },
    ],
  },
  {
    id: 'p-2',
    rank: 2,
    name: 'DevSync Studio',
    handle: '@devsync_hq',
    university: 'BITS Pilani',
    city: 'Goa',
    avatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=250&q=80',
    category: 'AGENCY',
    isTeam: true,
    teamMembers: ['Rohan Patel', 'Siddharth V.', 'Kavya M.'],
    totalEarnings: 241000,
    earningsToday: 0,
    earningsWeek: 42000,
    verifiedCount: 11,
    rankDelta24h: -1,
    isVelocityHigh: false,
    hustleTitle: 'Full-Stack Web Development Agency',
    proofs: [],
  },
  {
    id: 'p-3',
    rank: 3,
    name: 'Ananya Roy',
    handle: '@ananyadesigns',
    university: 'NID Ahmedabad / IIT Bombay',
    city: 'Mumbai',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    category: 'DESIGN',
    isTeam: false,
    totalEarnings: 198500,
    earningsToday: 24000,
    earningsWeek: 58000,
    verifiedCount: 9,
    rankDelta24h: 2,
    isVelocityHigh: true,
    hustleTitle: 'Figma UI/UX & Design Systems',
    proofs: [],
  },
  {
    id: 'p-4',
    rank: 4,
    name: 'Vikram & Yash (DropScale)',
    handle: '@dropscale_in',
    university: 'DTU Delhi',
    city: 'Delhi NCR',
    avatar: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=250&q=80',
    category: 'COMMERCE',
    isTeam: true,
    teamMembers: ['Vikram Singh', 'Yash Gupta'],
    totalEarnings: 172000,
    earningsToday: 12500,
    earningsWeek: 39000,
    verifiedCount: 18,
    rankDelta24h: 3,
    isVelocityHigh: true,
    hustleTitle: 'D2C Brand & Shopify Dropshipping',
    proofs: [],
  },
];

module.exports = { MOCK_PARTICIPANTS };
